In [1]:
import pandas as pd
import requests

In [2]:
# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [3]:
df.head(5)

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975

In [4]:
df.rename(columns={"entity": "Pais", "code": "Codigo", "year": "Anio", "life_expectancy_0": "Esperanza de Vida"}, inplace=True)

In [5]:
df.head(3)

          Pais Codigo  Anio  Esperanza de Vida
0  Afghanistan    AFG  1950            28.1563
1  Afghanistan    AFG  1951            28.5836
2  Afghanistan    AFG  1952            29.0138

In [6]:
df.set_index("Pais")

            Codigo  Anio  Esperanza de Vida
Pais
Afghanistan    AFG  1950            28.1563
Afghanistan    AFG  1951            28.5836
Afghanistan    AFG  1952            29.0138
Afghanistan    AFG  1953            29.4521
Afghanistan    AFG  1954            29.6975
...            ...   ...                ...
Zimbabwe       ZWE  2019            61.0603
Zimbabwe       ZWE  2020            61.5300
Zimbabwe       ZWE  2021            60.1347
Zimbabwe       ZWE  2022            62.3601
Zimbabwe       ZWE  2023            62.7748

[21565 rows x 3 columns]

In [7]:
df.loc[df["Pais"].str.contains("I", case=False, regex=True)]

              Pais Codigo  Anio  Esperanza de Vida
0      Afghanistan    AFG  1950            28.1563
1      Afghanistan    AFG  1951            28.5836
2      Afghanistan    AFG  1952            29.0138
3      Afghanistan    AFG  1953            29.4521
4      Afghanistan    AFG  1954            29.6975
...            ...    ...   ...                ...
21560     Zimbabwe    ZWE  2019            61.0603
21561     Zimbabwe    ZWE  2020            61.5300
21562     Zimbabwe    ZWE  2021            60.1347
21563     Zimbabwe    ZWE  2022            62.3601
21564     Zimbabwe    ZWE  2023            62.7748

[13468 rows x 4 columns]

In [8]:
df.loc[df["Codigo"].isnull()]

                                        Pais Codigo  Anio  Esperanza de Vida
375                                 Americas    NaN  1770            34.8000
376                                 Americas    NaN  1830            34.8000
377                                 Americas    NaN  1850            35.1000
378                                 Americas    NaN  1870            35.1000
379                                 Americas    NaN  1900            41.0000
...                                      ...    ...   ...                ...
17703  Small Island Developing States (SIDS)    NaN  2019            72.0847
17704  Small Island Developing States (SIDS)    NaN  2020            71.7761
17705  Small Island Developing States (SIDS)    NaN  2021            69.8938
17706  Small Island Developing States (SIDS)    NaN  2022            72.1257
17707  Small Island Developing States (SIDS)    NaN  2023            72.7255

[1348 rows x 4 columns]

In [9]:
df.dropna(subset=["Codigo"], inplace=True)
df.isnull().sum()

Pais                 0
Codigo               0
Anio                 0
Esperanza de Vida    0
dtype: int64

In [10]:
resultado = (
    df.loc[df["Anio"] == 2020]
    .groupby("Pais")["Esperanza de Vida"]
    .mean()
    .sort_values(ascending=True)
)

resultado.head(10)

Pais
Central African Republic    50.5959
Nigeria                     53.0724
Chad                        53.0818
Lesotho                     55.1325
Somalia                     57.0948
South Sudan                 57.6479
Mali                        58.8577
Guinea                      59.3499
Sierra Leone                59.6935
Eswatini                    59.8618
Name: Esperanza de Vida, dtype: float64

In [11]:
memoria = df.memory_usage(deep=True).sum() / 1024 ** 2
print(f"Memoria utilizada: {memoria:.2f} MB")

Memoria utilizada: 2.59 MB